export default [
  {
    day: 1, topic: 'Greetings',
    phrases: [
      { english: 'Hello! (informal)', russian: 'Привет!', breakdown: 'pri-VYET' },
      { english: 'Hello! (formal)', russian: 'Здравствуйте!', breakdown: 'ZDRA-stvuy-tye' },
      { english: 'Good morning', russian: 'Доброе утро', breakdown: 'DOB-ro-ye OO-tro' },
      { english: 'Good afternoon', russian: 'Добрый день', breakdown: 'DOB-riy dyen\'  (soft N)' },
      { english: 'Good evening', russian: 'Добрый вечер', breakdown: 'DOB-riy VYE-cher' },
      { english: 'How are you?', russian: 'Как дела?', breakdown: 'kak dye-LA? (stress on last)' },
    ],
  },
  {
    day: 2, topic: 'Introductions',
    phrases: [
      { english: 'My name is...', russian: 'Меня зовут...', breakdown: 'me-NYA zo-VOOT' },
      { english: 'What is your name?', russian: 'Как вас зовут?', breakdown: 'kak vas zo-VOOT?' },
      { english: 'Nice to meet you!', russian: 'Приятно познакомиться!', breakdown: 'pri-YAT-no poz-na-KO-mit-sya' },
      { english: 'I am from...', russian: 'Я из...', breakdown: 'ya iz' },
      { english: 'Where are you from?', russian: 'Откуда вы?', breakdown: 'ot-KOO-da vy?' },
      { english: 'I am ... years old.', russian: 'Мне ... лет.', breakdown: 'mnye ... lyet' },
    ],
  },
  {
    day: 3, topic: 'Numbers 1–10',
    phrases: [
      { english: 'One', russian: 'Один', breakdown: 'a-DEEN' },
      { english: 'Two', russian: 'Два', breakdown: 'dva' },
      { english: 'Three', russian: 'Три', breakdown: 'tree' },
      { english: 'Four', russian: 'Четыре', breakdown: 'che-TY-rye' },
      { english: 'Five', russian: 'Пять', breakdown: 'pyat\'' },
      { english: 'Six / Seven / Eight', russian: 'Шесть / Семь / Восемь', breakdown: 'shest\' / syem\' / VO-syem\'' },
    ],
  },
  {
    day: 4, topic: 'Time & Days',
    phrases: [
      { english: 'What time is it?', russian: 'Который час?', breakdown: 'ko-TO-riy chas?' },
      { english: 'Today', russian: 'Сегодня', breakdown: 'se-VOD-nya (г sounds like V)' },
      { english: 'Tomorrow', russian: 'Завтра', breakdown: 'ZAV-tra' },
      { english: 'Yesterday', russian: 'Вчера', breakdown: 'vche-RA' },
      { english: 'In the morning', russian: 'Утром', breakdown: 'OO-trom' },
      { english: 'In the evening', russian: 'Вечером', breakdown: 'VYE-che-rom' },
    ],
  },
  {
    day: 5, topic: 'Colors',
    phrases: [
      { english: 'Red', russian: 'Красный', breakdown: 'KRAS-niy' },
      { english: 'Blue', russian: 'Синий', breakdown: 'SEE-niy' },
      { english: 'Green', russian: 'Зелёный', breakdown: 'ze-LYO-niy' },
      { english: 'Yellow', russian: 'Жёлтый', breakdown: 'ZHOL-tiy' },
      { english: 'White', russian: 'Белый', breakdown: 'BYE-liy' },
      { english: 'Black', russian: 'Чёрный', breakdown: 'CHOR-niy' },
    ],
  },
  {
    day: 6, topic: 'Family',
    phrases: [
      { english: 'Mom / Dad', russian: 'Мама / Папа', breakdown: 'MA-ma / PA-pa' },
      { english: 'Brother', russian: 'Брат', breakdown: 'brat' },
      { english: 'Sister', russian: 'Сестра', breakdown: 'ses-TRA' },
      { english: 'Grandmother', russian: 'Бабушка', breakdown: 'BA-boosh-ka' },
      { english: 'Grandfather', russian: 'Дедушка', breakdown: 'DYE-doosh-ka' },
      { english: 'My family is big.', russian: 'Моя семья большая.', breakdown: 'mo-YA sem-YA bol-SHA-ya' },
    ],
  },
  {
    day: 7, topic: 'Food Basics',
    phrases: [
      { english: 'Bread', russian: 'Хлеб', breakdown: 'khlyeb' },
      { english: 'Water', russian: 'Вода', breakdown: 'vo-DA' },
      { english: 'Coffee', russian: 'Кофе', breakdown: 'KO-fye' },
      { english: 'Tea', russian: 'Чай', breakdown: 'chay' },
      { english: 'Meat', russian: 'Мясо', breakdown: 'MYA-so' },
      { english: 'Vegetables / Fruit', russian: 'Овощи / Фрукты', breakdown: 'O-vo-shchi / FROOK-ty' },
    ],
  },
  {
    day: 8, topic: 'At a Café',
    phrases: [
      { english: 'Can I have the menu?', russian: 'Можно меню?', breakdown: 'MOZH-no me-NYU?' },
      { english: 'I want...', russian: 'Я хочу...', breakdown: 'ya kho-CHOO' },
      { english: 'The bill, please!', russian: 'Счёт, пожалуйста!', breakdown: 'shot, po-ZHA-luy-sta' },
      { english: 'Very delicious!', russian: 'Очень вкусно!', breakdown: 'O-chen\' VKOOS-no' },
      { english: 'What do you recommend?', russian: 'Что вы рекомендуете?', breakdown: 'shto vy re-ko-men-DOO-ye-tye?' },
      { english: 'Without sugar', russian: 'Без сахара', breakdown: 'byez SA-kha-ra' },
    ],
  },
  {
    day: 9, topic: 'Directions',
    phrases: [
      { english: 'Where is...?', russian: 'Где находится...?', breakdown: 'gdye na-KHO-dit-sya?' },
      { english: 'To the left', russian: 'Налево', breakdown: 'na-LYE-vo' },
      { english: 'To the right', russian: 'Направо', breakdown: 'na-PRA-vo' },
      { english: 'Straight ahead', russian: 'Прямо', breakdown: 'PRYA-mo' },
      { english: 'Nearby', russian: 'Рядом', breakdown: 'RYA-dom' },
      { english: 'Far away / Close', russian: 'Далеко / Близко', breakdown: 'da-le-KO / BLEES-ko' },
    ],
  },
  {
    day: 10, topic: 'Transport',
    phrases: [
      { english: 'Metro / Subway', russian: 'Метро', breakdown: 'met-RO' },
      { english: 'Bus', russian: 'Автобус', breakdown: 'av-TO-boos' },
      { english: 'Taxi', russian: 'Такси', breakdown: 'tak-SEE' },
      { english: 'Train', russian: 'Поезд', breakdown: 'PO-yezd' },
      { english: 'How do I get to...?', russian: 'Как доехать до...?', breakdown: 'kak do-YE-khat\' do?' },
      { english: 'Next stop is...', russian: 'Следующая остановка...', breakdown: 'SLYE-doo-yu-sha-ya os-ta-NOV-ka' },
    ],
  },
  {
    day: 11, topic: 'Shopping',
    phrases: [
      { english: 'How much does this cost?', russian: 'Сколько это стоит?', breakdown: 'SKOL\'-ko E-to STO-it?' },
      { english: 'It\'s expensive.', russian: 'Дорого.', breakdown: 'DO-ro-go' },
      { english: 'It\'s cheap.', russian: 'Дёшево.', breakdown: 'DYO-she-vo' },
      { english: 'I\'ll take this.', russian: 'Я возьму это.', breakdown: 'ya voz\'-MOO E-to' },
      { english: 'Where is the cashier?', russian: 'Где касса?', breakdown: 'gdye KAS-sa?' },
      { english: 'Is there a discount?', russian: 'Есть скидка?', breakdown: 'yest\' SKEED-ka?' },
    ],
  },
  {
    day: 12, topic: 'Weather',
    phrases: [
      { english: 'What\'s the weather today?', russian: 'Какая сегодня погода?', breakdown: 'ka-KA-ya se-VOD-nya po-GO-da?' },
      { english: 'It\'s sunny!', russian: 'Солнечно!', breakdown: 'SOL-nech-no' },
      { english: 'It\'s raining.', russian: 'Идёт дождь.', breakdown: 'i-DYOT dozhd\'' },
      { english: 'It\'s cold.', russian: 'Холодно.', breakdown: 'KHO-lod-no' },
      { english: 'It\'s hot.', russian: 'Жарко.', breakdown: 'ZHAR-ko' },
      { english: 'It\'s snowing.', russian: 'Идёт снег.', breakdown: 'i-DYOT snyek' },
    ],
  },
  {
    day: 13, topic: 'Feelings & Emotions',
    phrases: [
      { english: 'I am happy!', russian: 'Я счастлив! / Я счастлива!', breakdown: 'ya SCHAST-leev (m) / SCHAST-lee-va (f)' },
      { english: 'I feel sad.', russian: 'Мне грустно.', breakdown: 'mnye GROOS-tno' },
      { english: 'I am tired.', russian: 'Я устал. / Я устала.', breakdown: 'ya oos-TAL (m) / oos-TA-la (f)' },
      { english: 'I love you.', russian: 'Я люблю тебя.', breakdown: 'ya lyub-LYOO te-BYA' },
      { english: 'I\'m glad to see you!', russian: 'Я рад тебя видеть!', breakdown: 'ya rad te-BYA VEE-dyet\'' },
      { english: 'I\'m worried.', russian: 'Я беспокоюсь.', breakdown: 'ya byes-po-KO-yoos\'' },
    ],
  },
  {
    day: 14, topic: 'Body & Health',
    phrases: [
      { english: 'I have a headache.', russian: 'У меня болит голова.', breakdown: 'oo me-NYA bo-LEET go-lo-VA' },
      { english: 'Arm / Hand', russian: 'Рука', breakdown: 'roo-KA' },
      { english: 'Leg / Foot', russian: 'Нога', breakdown: 'no-GA' },
      { english: 'Back', russian: 'Спина', breakdown: 'spi-NA' },
      { english: 'I feel unwell.', russian: 'Мне плохо.', breakdown: 'mnye PLO-kho' },
      { english: 'Call a doctor!', russian: 'Вызовите врача!', breakdown: 'VY-zo-vee-tye vra-CHA!' },
    ],
  },
  {
    day: 15, topic: 'At the Doctor',
    phrases: [
      { english: 'I need a doctor.', russian: 'Мне нужен врач.', breakdown: 'mnye NOO-zhen vrach' },
      { english: 'I have a fever.', russian: 'У меня температура.', breakdown: 'oo me-NYA tem-pe-ra-TOO-ra' },
      { english: 'I have an allergy.', russian: 'У меня аллергия.', breakdown: 'oo me-NYA al-ler-GEE-ya' },
      { english: 'Where is the pharmacy?', russian: 'Где аптека?', breakdown: 'gdye ap-TYE-ka?' },
      { english: 'What medicine should I take?', russian: 'Какое лекарство принимать?', breakdown: 'ka-KO-ye le-KARS-tvo pri-ni-MAT\'' },
      { english: 'I feel better now.', russian: 'Мне уже лучше.', breakdown: 'mnye oo-ZHYE LOOCH-she' },
    ],
  },
  {
    day: 16, topic: 'Hobbies',
    phrases: [
      { english: 'I love to read.', russian: 'Я люблю читать.', breakdown: 'ya lyub-LYOO chi-TAT\'' },
      { english: 'I do sports.', russian: 'Я занимаюсь спортом.', breakdown: 'ya za-ni-MA-yus\' SPOR-tom' },
      { english: 'I listen to music.', russian: 'Я слушаю музыку.', breakdown: 'ya SLOO-sha-yu MOO-zy-ku' },
      { english: 'I play guitar.', russian: 'Я играю на гитаре.', breakdown: 'ya ig-RA-yu na gi-TA-rye' },
      { english: 'I watch movies.', russian: 'Я смотрю фильмы.', breakdown: 'ya smot-RYOO FEEL\'-my' },
      { english: 'What is your hobby?', russian: 'Какое у тебя хобби?', breakdown: 'ka-KO-ye oo te-BYA KHOB-bi?' },
    ],
  },
  {
    day: 17, topic: 'Work & Professions',
    phrases: [
      { english: 'What do you do for work?', russian: 'Кем вы работаете?', breakdown: 'kyem vy ra-BO-ta-ye-tye?' },
      { english: 'I work in an office.', russian: 'Я работаю в офисе.', breakdown: 'ya ra-BO-ta-yu v O-fi-se' },
      { english: 'My colleague', russian: 'Мой коллега', breakdown: 'moy kol-LYE-ga' },
      { english: 'Boss / Manager', russian: 'Начальник', breakdown: 'na-CHAL\'-nik' },
      { english: 'I have a meeting.', russian: 'У меня встреча.', breakdown: 'oo me-NYA VSTRY-e-cha' },
      { english: 'I am busy.', russian: 'Я занят. / Я занята.', breakdown: 'ya ZA-nyat (m) / za-nya-TA (f)' },
    ],
  },
  {
    day: 18, topic: 'Home',
    phrases: [
      { english: 'House / Apartment', russian: 'Дом / Квартира', breakdown: 'dom / kvar-TEE-ra' },
      { english: 'Kitchen', russian: 'Кухня', breakdown: 'KOOKH-nya' },
      { english: 'Bedroom', russian: 'Спальня', breakdown: 'SPAL\'-nya' },
      { english: 'Bathroom', russian: 'Ванная', breakdown: 'VAN-na-ya' },
      { english: 'Welcome!', russian: 'Добро пожаловать!', breakdown: 'dob-RO po-ZHA-lo-vat\'' },
      { english: 'Make yourself at home.', russian: 'Чувствуйте себя как дома.', breakdown: 'CHOOST-vooy-tye se-BYA kak DO-ma' },
    ],
  },
  {
    day: 19, topic: 'Nature',
    phrases: [
      { english: 'Forest', russian: 'Лес', breakdown: 'lyes' },
      { english: 'Sea / River', russian: 'Море / Река', breakdown: 'MO-rye / re-KA' },
      { english: 'Mountains', russian: 'Горы', breakdown: 'GO-ry' },
      { english: 'Flower', russian: 'Цветок', breakdown: 'tsve-TOK' },
      { english: 'Beautiful nature!', russian: 'Красивая природа!', breakdown: 'kra-SEE-va-ya pri-RO-da!' },
      { english: 'I love nature.', russian: 'Я люблю природу.', breakdown: 'ya lyub-LYOO pri-RO-doo' },
    ],
  },
  {
    day: 20, topic: 'Seasons',
    phrases: [
      { english: 'Spring / Summer', russian: 'Весна / Лето', breakdown: 'ves-NA / LYE-to' },
      { english: 'Autumn / Winter', russian: 'Осень / Зима', breakdown: 'O-sen\' / zi-MA' },
      { english: 'I love summer!', russian: 'Мне нравится лето!', breakdown: 'mnye NRA-vit-sya LYE-to!' },
      { english: 'In winter it\'s very cold.', russian: 'Зимой очень холодно.', breakdown: 'zi-MOY O-chen\' KHO-lod-no' },
      { english: 'It\'s warm in spring.', russian: 'Весной тепло.', breakdown: 'ves-NOY tep-LO' },
      { english: 'Autumn is beautiful.', russian: 'Осень прекрасна.', breakdown: 'O-sen\' pre-KRAS-na' },
    ],
  },
  {
    day: 21, topic: 'Travel',
    phrases: [
      { english: 'Airport', russian: 'Аэропорт', breakdown: 'a-e-ro-PORT' },
      { english: 'Airplane', russian: 'Самолёт', breakdown: 'sa-mo-LYOT' },
      { english: 'Passport', russian: 'Паспорт', breakdown: 'PAS-port' },
      { english: 'Luggage', russian: 'Багаж', breakdown: 'ba-GAZH' },
      { english: 'Hotel', russian: 'Гостиница', breakdown: 'gos-TEE-ni-tsa' },
      { english: 'Where is my suitcase?', russian: 'Где мой чемодан?', breakdown: 'gdye moy che-mo-DAN?' },
    ],
  },
  {
    day: 22, topic: 'Phone Calls',
    phrases: [
      { english: 'Hello! (on phone)', russian: 'Алло!', breakdown: 'al-LO!' },
      { english: 'Can I speak with...?', russian: 'Можно поговорить с...?', breakdown: 'MOZH-no po-go-vo-REET\' s?' },
      { english: 'Call me back.', russian: 'Перезвоните мне.', breakdown: 'pe-re-zvo-NEE-tye mnye' },
      { english: 'I can\'t hear you.', russian: 'Я вас не слышу.', breakdown: 'ya vas nye SLYSH-shoo' },
      { english: 'Leave a message.', russian: 'Оставьте сообщение.', breakdown: 'os-TAV\'-tye so-ob-SHCHE-ni-ye' },
      { english: 'I\'ll call back later.', russian: 'Я перезвоню позже.', breakdown: 'ya pe-re-zvo-NYOO POZ-zhe' },
    ],
  },
  {
    day: 23, topic: 'Making Plans',
    phrases: [
      { english: 'Let\'s meet!', russian: 'Давай встретимся!', breakdown: 'da-VAY vstRYE-tim-sya!' },
      { english: 'When are you free?', russian: 'Когда ты свободен?', breakdown: 'kog-DA ty svo-BO-den?' },
      { english: 'At what time?', russian: 'В котором часу?', breakdown: 'f ko-TO-rom cha-SOO?' },
      { english: 'It\'s a deal! / Agreed!', russian: 'Договорились!', breakdown: 'do-go-vo-REE-lis\'' },
      { english: 'Where shall we meet?', russian: 'Где встретимся?', breakdown: 'gdye vstRYE-tim-sya?' },
      { english: 'I\'m looking forward to it!', russian: 'Я с нетерпением жду!', breakdown: 'ya s nye-ter-PYE-ni-yem zdoo' },
    ],
  },
  {
    day: 24, topic: 'Politeness',
    phrases: [
      { english: 'Please / You\'re welcome', russian: 'Пожалуйста', breakdown: 'po-ZHA-luy-sta' },
      { english: 'Thank you very much!', russian: 'Спасибо большое!', breakdown: 'spa-SEE-bo bol\'-SHO-ye!' },
      { english: 'Excuse me.', russian: 'Извините.', breakdown: 'iz-vi-NEE-tye' },
      { english: 'I\'m sorry.', russian: 'Простите меня.', breakdown: 'pros-TEE-tye me-NYA' },
      { english: 'Don\'t mention it.', russian: 'Не за что.', breakdown: 'NYE za chto' },
      { english: 'Everything is fine!', russian: 'Всё в порядке!', breakdown: 'vsyo f po-RYAD-kye!' },
    ],
  },
  {
    day: 25, topic: 'Russian Culture',
    phrases: [
      { english: 'Blini — Russian pancakes', russian: 'Блины', breakdown: 'bli-NY' },
      { english: 'Happy New Year!', russian: 'С Новым годом!', breakdown: 's NO-vym GO-dom!' },
      { english: 'Be healthy! / Bless you!', russian: 'Будьте здоровы!', breakdown: 'BOOD\'-tye zdo-RO-vy!' },
      { english: 'Soul (key Russian concept)', russian: 'Душа', breakdown: 'doo-SHA' },
      { english: 'To your health!', russian: 'На здоровье!', breakdown: 'na zdo-RO-vye!' },
      { english: 'White nights (St. Petersburg)', russian: 'Белые ночи', breakdown: 'BYE-ly-ye NO-chi' },
    ],
  },
  {
    day: 26, topic: 'Sports',
    phrases: [
      { english: 'Football / Hockey', russian: 'Футбол / Хоккей', breakdown: 'foot-BOL / khok-KYEY' },
      { english: 'I run every morning.', russian: 'Я бегаю каждое утро.', breakdown: 'ya BYE-ga-yu KAZH-do-ye OO-tro' },
      { english: 'I swim.', russian: 'Я плаваю.', breakdown: 'ya PLA-va-yu' },
      { english: 'Who won?', russian: 'Кто победил?', breakdown: 'kto po-be-DEEL?' },
      { english: 'Our team won!', russian: 'Наша команда выиграла!', breakdown: 'NA-sha ko-MAN-da VY-ig-ra-la!' },
      { english: 'I play tennis.', russian: 'Я играю в теннис.', breakdown: 'ya ig-RA-yu f TEN-nis' },
    ],
  },
  {
    day: 27, topic: 'Movies & Music',
    phrases: [
      { english: 'What\'s your favorite movie?', russian: 'Какой твой любимый фильм?', breakdown: 'ka-KOY tvoy lyoo-BEE-miy feel\'-m?' },
      { english: 'I want to go to the cinema.', russian: 'Я хочу в кино.', breakdown: 'ya kho-CHOO v ki-NO' },
      { english: 'What music do you listen to?', russian: 'Какую музыку ты слушаешь?', breakdown: 'ka-KOO-yu MOO-zy-ku ty SLOO-sha-yesh\'' },
      { english: 'Amazing concert!', russian: 'Потрясающий концерт!', breakdown: 'pot-rya-SA-yu-shchiy kon-TSERT!' },
      { english: 'I\'m reading a book.', russian: 'Я читаю книгу.', breakdown: 'ya chi-TA-yu KNEE-goo' },
      { english: 'What do you recommend to watch?', russian: 'Что посоветуешь посмотреть?', breakdown: 'shto po-so-VYE-tu-yesh\' pos-mot-RYET\'' },
    ],
  },
  {
    day: 28, topic: 'News & Opinions',
    phrases: [
      { english: 'Did you hear?', russian: 'Ты слышал? / Ты слышала?', breakdown: 'ty SLY-shal (m) / SLY-sha-la (f)?' },
      { english: 'What happened?', russian: 'Что случилось?', breakdown: 'shto sloo-CHEE-los\'' },
      { english: 'In my opinion...', russian: 'По-моему...', breakdown: 'po-MO-ye-mu' },
      { english: 'I agree.', russian: 'Я согласен. / Я согласна.', breakdown: 'ya sog-LA-sen (m) / sog-LAS-na (f)' },
      { english: 'This is very important!', russian: 'Это очень важно!', breakdown: 'E-to O-chen\' VAZH-no!' },
      { english: 'I think that...', russian: 'Я думаю, что...', breakdown: 'ya DOO-ma-yu shto' },
    ],
  },
  {
    day: 29, topic: 'Connectors & Flow',
    phrases: [
      { english: 'Because...', russian: 'Потому что...', breakdown: 'po-to-MOO shto' },
      { english: 'Therefore...', russian: 'Поэтому...', breakdown: 'po-E-to-mu' },
      { english: 'However...', russian: 'Однако...', breakdown: 'od-NA-ko' },
      { english: 'By the way...', russian: 'Кстати...', breakdown: 'KSTA-ti' },
      { english: 'First of all...', russian: 'Во-первых...', breakdown: 'vo-PYER-vykh' },
      { english: 'For example...', russian: 'Например...', breakdown: 'na-pri-MYER' },
    ],
  },
  {
    day: 30, topic: 'Graduation Day!',
    phrases: [
      { english: 'I speak Russian!', russian: 'Я говорю по-русски!', breakdown: 'ya go-vo-RYOO po-ROOS-ki!' },
      { english: 'I learn every day.', russian: 'Я учусь каждый день.', breakdown: 'ya oo-CHOOS\' KAZH-dy dyen\'' },
      { english: 'Thank you for the help!', russian: 'Спасибо за помощь!', breakdown: 'spa-SEE-bo za PO-moshch\'' },
      { english: 'Goodbye! (formal)', russian: 'До свидания!', breakdown: 'do svi-DA-ni-ya' },
      { english: 'See you!', russian: 'Увидимся!', breakdown: 'oo-VEE-dim-sya' },
      { english: 'Well done! / Good job!', russian: 'Молодец!', breakdown: 'mo-lo-DETS!' },
    ],
  },
];
